parameters:
  ServiceDirectory: ''
  Artifacts: []
  AdditionalModules: []
  EnvVars: {}
  MaxParallel: 0
  Matrix:
    # US Gov
    Linux - Java 8 (AzureUSGovernment):
      OSName: 'Linux'
      OSVmImage: 'ubuntu-18.04'
      JavaVersion: '1.8'
      DisplayName: 'Linux - Java 8'
      CloudType: AzureUSGovernment
      AZURE_TEST_HTTP_CLIENTS: netty
      AZURE_AUTHORITY_HOST: $(aad-azure-sdk-test-authority-host-gov)
      ArmTemplateParameters: $(azureUSGovernmentArmParameters)
      ARM_CLIENTID: $(aad-azure-sdk-test-client-id-gov)
      ARM_CLIENTKEY: $(aad-azure-sdk-test-client-secret-gov)
      AZURE_TENANT_ID: $(aad-azure-sdk-test-tenant-id-gov)
    # macOS - Java 8 (AzureUSGovernment):
    #   OSName: 'macOS'
    #   OSVmImage: 'macOS-10.15'
    #   JavaVersion: '1.8'
    #   DisplayName: 'macOS - Java 8'
    #   CloudType: AzureUSGovernment
    #   AZURE_TEST_HTTP_CLIENTS: okhttp
    # AZURE_AUTHORITY_HOST: $(aad-azure-sdk-test-authority-host-gov)
    # ArmTemplateParameters: $(azureUSGovernmentArmParameters)
    # ARM_CLIENTID: $(aad-azure-sdk-test-client-id-gov)
    #   ARM_CLIENTKEY: $(aad-azure-sdk-test-client-secret-gov)
    #   AZURE_TENANT_ID: $(aad-azure-sdk-test-tenant-id-gov)
    Windows - Java 8 (AzureUSGovernment):
      OSName: 'Windows'
      OSVmImage: 'windows-2019'
      JavaVersion: '1.8'
      DisplayName: 'Windows - Java 8'
      CloudType: AzureUSGovernment
      AZURE_TEST_HTTP_CLIENTS: netty
      AZURE_AUTHORITY_HOST: $(aad-azure-sdk-test-authority-host-gov)
      ArmTemplateParameters: $(azureUSGovernmentArmParameters)
      ARM_CLIENTID: $(aad-azure-sdk-test-client-id-gov)
      ARM_CLIENTKEY: $(aad-azure-sdk-test-client-secret-gov)
      AZURE_TENANT_ID: $(aad-azure-sdk-test-tenant-id-gov)
    # Linux - Java 11 (AzureUSGovernment):
    #   OSName: 'Linux'
    #   OSVmImage: 'ubuntu-18.04'
    #   JavaVersion: '1.11'
    #   DisplayName: 'Linux - Java 11'
    #   CloudType: AzureUSGovernment
    #   AZURE_TEST_HTTP_CLIENTS: okhttp
    # AZURE_AUTHORITY_HOST: $(aad-azure-sdk-test-authority-host-gov)
    # ArmTemplateParameters: $(azureUSGovernmentArmParameters)
    # ARM_CLIENTID: $(aad-azure-sdk-test-client-id-gov)
    #   ARM_CLIENTKEY: $(aad-azure-sdk-test-client-secret-gov)
    #   AZURE_TENANT_ID: $(aad-azure-sdk-test-tenant-id-gov)
    # macOS - Java 11 (AzureUSGovernment):
    #   OSName: 'macOS'
    #   OSVmImage: 'macOS-10.15'
    #   JavaVersion: '1.11'
    #   DisplayName: 'macOS - Java 11'
    #   CloudType: AzureUSGovernment
    #   AZURE_TEST_HTTP_CLIENTS: netty
    # AZURE_AUTHORITY_HOST: $(aad-azure-sdk-test-authority-host-gov)
    # ArmTemplateParameters: $(azureUSGovernmentArmParameters)
    # ARM_CLIENTID: $(aad-azure-sdk-test-client-id-gov)
    #   ARM_CLIENTKEY: $(aad-azure-sdk-test-client-secret-gov)
    #   AZURE_TENANT_ID: $(aad-azure-sdk-test-tenant-id-gov)
    Windows - Java 11 (AzureUSGovernment):
      OSName: 'Windows'
      OSVmImage: 'windows-2019'
      JavaVersion: '1.11'
      DisplayName: 'Windows - Java 11'
      CloudType: AzureUSGovernment
      AZURE_TEST_HTTP_CLIENTS: okhttp
      AZURE_AUTHORITY_HOST: $(aad-azure-sdk-test-authority-host-gov)
      ArmTemplateParameters: $(azureUSGovernmentArmParameters)
      ARM_CLIENTID: $(aad-azure-sdk-test-client-id-gov)
      ARM_CLIENTKEY: $(aad-azure-sdk-test-client-secret-gov)
      AZURE_TENANT_ID: $(aad-azure-sdk-test-tenant-id-gov)

    # China
    Linux - Java 8 (AzureChinaCloud):
      OSName: 'Linux'
      OSVmImage: 'ubuntu-18.04'
      JavaVersion: '1.8'
      DisplayName: 'Linux - Java 8'
      CloudType: AzureChinaCloud
      AZURE_TEST_HTTP_CLIENTS: netty
      AZURE_AUTHORITY_HOST: $(aad-azure-sdk-test-authority-host-cn)
      ArmTemplateParameters: $(azureChinaCloudArmParameters)
      ARM_CLIENTID: $(aad-azure-sdk-test-client-id-cn)
      ARM_CLIENTKEY: $(aad-azure-sdk-test-client-secret-cn)
      AZURE_TENANT_ID: $(aad-azure-sdk-test-tenant-id-cn)
    # macOS - Java 8 (AzureChinaCloud):
    #   OSName: 'macOS'
    #   OSVmImage: 'macOS-10.15'
    #   JavaVersion: '1.8'
    #   DisplayName: 'macOS - Java 8'
    #   CloudType: AzureChinaCloud
    #   AZURE_TEST_HTTP_CLIENTS: okhttp
    # AZURE_AUTHORITY_HOST: $(aad-azure-sdk-test-authority-host-cn)
    # ArmTemplateParameters: $(azureChinaCloudArmParameters)
    # ARM_CLIENTID: $(aad-azure-sdk-test-client-id-cn)
    #   ARM_CLIENTKEY: $(aad-azure-sdk-test-client-secret-cn)
    #   AZURE_TENANT_ID: $(aad-azure-sdk-test-tenant-id-cn)
    Windows - Java 8 (AzureChinaCloud):
      OSName: 'Windows'
      OSVmImage: 'windows-2019'
      JavaVersion: '1.8'
      DisplayName: 'Windows - Java 8'
      CloudType: AzureChinaCloud
      AZURE_TEST_HTTP_CLIENTS: netty
      AZURE_AUTHORITY_HOST: $(aad-azure-sdk-test-authority-host-cn)
      ArmTemplateParameters: $(azureChinaCloudArmParameters)
      ARM_CLIENTID: $(aad-azure-sdk-test-client-id-cn)
      ARM_CLIENTKEY: $(aad-azure-sdk-test-client-secret-cn)
      AZURE_TENANT_ID: $(aad-azure-sdk-test-tenant-id-cn)
    # Linux - Java 11 (AzureChinaCloud):
    #   OSName: 'Linux'
    #   OSVmImage: 'ubuntu-18.04'
    #   JavaVersion: '1.11'
    #   DisplayName: 'Linux - Java 11'
    #   CloudType: AzureChinaCloud
    #   AZURE_TEST_HTTP_CLIENTS: okhttp
    # AZURE_AUTHORITY_HOST: $(aad-azure-sdk-test-authority-host-cn)
    # ArmTemplateParameters: $(azureChinaCloudArmParameters)
    # ARM_CLIENTID: $(aad-azure-sdk-test-client-id-cn)
    #   ARM_CLIENTKEY: $(aad-azure-sdk-test-client-secret-cn)
    #   AZURE_TENANT_ID: $(aad-azure-sdk-test-tenant-id-cn)
    # macOS - Java 11 (AzureChinaCloud):
    #   OSName: 'macOS'
    #   OSVmImage: 'macOS-10.15'
    #   JavaVersion: '1.11'
    #   DisplayName: 'macOS - Java 11'
    #   CloudType: AzureChinaCloud
    #   AZURE_TEST_HTTP_CLIENTS: netty
    # AZURE_AUTHORITY_HOST: $(aad-azure-sdk-test-authority-host-cn)
    # ArmTemplateParameters: $(azureChinaCloudArmParameters)
    # ARM_CLIENTID: $(aad-azure-sdk-test-client-id-cn)
    #   ARM_CLIENTKEY: $(aad-azure-sdk-test-client-secret-cn)
    #   AZURE_TENANT_ID: $(aad-azure-sdk-test-tenant-id-cn)
    Windows - Java 11 (AzureChinaCloud):
      OSName: 'Windows'
      OSVmImage: 'windows-2019'
      JavaVersion: '1.11'
      DisplayName: 'Windows - Java 11'
      CloudType: AzureChinaCloud
      AZURE_TEST_HTTP_CLIENTS: okhttp
      AZURE_AUTHORITY_HOST: $(aad-azure-sdk-test-authority-host-cn)
      ArmTemplateParameters: $(azureChinaCloudArmParameters)
      ARM_CLIENTID: $(aad-azure-sdk-test-client-id-cn)
      ARM_CLIENTKEY: $(aad-azure-sdk-test-client-secret-cn)
      AZURE_TENANT_ID: $(aad-azure-sdk-test-tenant-id-cn)
  PreRunSteps: []
  PostRunSteps: []
  TestName: LiveTest
  TimeoutInMinutes: 60
  TestStepMavenInputs:
    options: '-Dmaven.wagon.http.pool=false $(DefaultOptions) -pl $(ProjectList)'
    mavenOptions: '$(MemoryOptions) $(LoggingOptions)'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '$(JavaVersion)'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    goals: 'test'
  TestResultsFiles: ''

jobs:
  - job: ${{ parameters.TestName }}
    timeoutInMinutes: ${{ parameters.TimeoutInMinutes }}

    variables:
      - template: ../variables/globals.yml
      - name: azureUSGovernmentArmParameters
        value: "@{ endpointSuffix = '.vault.usgovcloudapi.net' }"
      - name: azureChinaCloudArmParameters
        value: "@{ endpointSuffix = '.vault.azure.cn'; }"

    strategy:
      matrix: ${{ parameters.Matrix }}
      maxParallel: ${{ parameters.MaxParallel }}

    pool:
      vmImage: $(OSVmImage)

    steps:
      - ${{ if ne(parameters.DisableAzureResourceCreation, 'true') }}:
        - template: /eng/common/TestResources/deploy-test-resources.yml
          parameters:
            ServiceDirectory: '${{ parameters.ServiceDirectory }}'

      - ${{ parameters.PreRunSteps }}

      - template: ../steps/generate-project-list.yml
        parameters:
          Artifacts: ${{parameters.Artifacts}}
          AdditionalModules: ${{parameters.AdditionalModules}}

      - task: Maven@3
        displayName: 'Build and Install'
        inputs:
          mavenPomFile: pom.xml
          goals: 'install'
          options: '$(DefaultOptions) -DskipTests -Dgpg.skip -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true -Dspotbugs.skip=true -Drevapi.skip=true -pl $(ProjectList) -am'
          mavenOptions: '$(MemoryOptions) $(LoggingOptions)'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false

      - task: Maven@3
        displayName: $(DisplayName)
        inputs:
          mavenPomFile: pom.xml
          ${{ insert }}: ${{ parameters.TestStepMavenInputs }}
        env: ${{ parameters.EnvVars }}

      - ${{ parameters.PostRunSteps }}

      - ${{ if ne(parameters.DisableAzureResourceCreation, 'true') }}:
        - template: /eng/common/TestResources/remove-test-resources.yml


      - task: PublishTestResults@2
        condition: always()
        inputs:
          mergeTestResults: true
          testRunTitle: 'Live tests for ${{ parameters.ServiceDirectory }} $(DisplayName)'
          ${{ if ne(parameters.TestResultsFiles, '') }}:
            testResultsFiles: ${{ parameters.TestResultsFiles }}
