trigger: none

jobs:
  - template: ../../eng/pipelines/templates/jobs/archetype-sdk-tests.yml
    parameters:
      TimeoutInMinutes: 240
      MaxParallel: 2
      ServiceDirectory: keyvault
      ArmTemplateParameters: "@{ endpointSuffix = 'vault.usgovcloudapi.net' }"
      CloudType: AzureUSGovernment
      Artifacts:
        - name: azure-security-keyvault-certificates
          groupId: com.azure
          safeName: azuresecuritykeyvaultcertificates
        - name: azure-security-keyvault-keys
          groupId: com.azure
          safeName: azuresecuritykeyvaultkeys
        - name: azure-security-keyvault-secrets
          groupId: com.azure
          safeName: azuresecuritykeyvaultsecrets
      EnvVars:
        AZURE_TEST_MODE: RECORD
        ARM_CLIENTID: $(aad-azure-sdk-test-client-id-gov)
        ARM_CLIENTKEY: $(aad-azure-sdk-test-client-secret-gov)
        AZURE_TENANT_ID: $(aad-azure-sdk-test-tenant-id-gov)
        AZURE_AUTHORITY_HOST: $(aad-azure-sdk-test-authority-host-gov)

  - template: ../../eng/pipelines/templates/jobs/archetype-sdk-tests.yml
    parameters:
      TimeoutInMinutes: 240
      MaxParallel: 2
      ServiceDirectory: keyvault
      ArmTemplateParameters: "@{ endpointSuffix = 'vault.azure.cn'; }"
      CloudType: AzureChinaCloud
      Artifacts:
        - name: azure-security-keyvault-certificates
          groupId: com.azure
          safeName: azuresecuritykeyvaultcertificates
        - name: azure-security-keyvault-keys
          groupId: com.azure
          safeName: azuresecuritykeyvaultkeys
        - name: azure-security-keyvault-secrets
          groupId: com.azure
          safeName: azuresecuritykeyvaultsecrets
      EnvVars:
        AZURE_TEST_MODE: RECORD
        ARM_CLIENTID: $(aad-azure-sdk-test-client-id-cn)
        ARM_CLIENTKEY: $(aad-azure-sdk-test-client-secret-cn)
        AZURE_TENANT_ID: $(aad-azure-sdk-test-tenant-id-cn)
        AZURE_AUTHORITY_HOST: $(aad-azure-sdk-test-authority-host-cn)
